*KEYWORD
*COMMENT
IMPORTANT NOTICE: The technical information, guidance, and
other statements contained in this document or otherwise
provided by 3M are based upon records, tests, or experience
that 3M believes to be reliable, but the accuracy,
completeness, and representative nature of such information
is not guaranteed. Such information is intended for people
with knowledge and technical skills sufficient to assess and
apply their own informed judgment to the information. No
license under any 3M or third party intellectual property
rights is granted or implied with this information.

PRODUCT SELECTION AND USE: Many factors beyond 3Ms control
and uniquely within users knowledge and control can affect
the use and performance of a 3M product in a particular
application. As a result, customer is solely responsible for
evaluating the product and determining whether it is
appropriate and suitable for customers application,
including conducting a workplace hazard assessment and
reviewing all applicable regulations and standards (e.g.,
OSHA, ANSI, etc.). Failure to properly evaluate, select, and
use a 3M product and appropriate safety products, or to meet
all applicable safety regulations, may result in injury,
sickness, death, and/or harm to property.

WARRANTY, LIMITED REMEDY, AND DISCLAIMER: Unless a different
warranty is specifically stated on the applicable 3M product
packaging or product literature (in which case such warranty
governs), 3M warrants that each 3M product meets the
applicable 3M product specification at the time 3M ships the
product.

3M MAKES NO OTHER WARRANTIES OR CONDITIONS, EXPRESS OR
IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTY
OR CONDITION OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE, OR ARISING OUT OF A COURSE OF DEALING, CUSTOM, OR
USAGE OF TRADE. If a 3M product does not conform to this
warranty, then the sole and exclusive remedy is, at 3Ms
option, replacement of the 3M product or refund of the
purchase price.

LIMITATION OF LIABILITY: Except for the limited remedy
stated above, and except to the extent prohibited by law, 3M
will not be liable for any loss or damage arising from or
related to the 3M product, whether direct, indirect,
special, incidental, or consequential (including, but not
limited to, lost profits or business opportunity),
regardless of the legal or equitable theory asserted,
including, but not limited to, warranty, contract,
negligence, or strict liability.

Verification Code: 259f00144a1b5f4c4f3d428fa861085158e5a49b7480b54a2ac16528c0befcf1

3M Material Data
Copyright 3M Company
Material model exported at 01:49 on 2021-01-28

sa_bt1
Unit system: in-lbf-s

Note that the material ID (MID) must be modified, as appropriate

*MAT_GENERAL_VISCOELASTIC
 1,  9.3573e-05,  7.7016e+06

  1.2119e+04,  1.0000e+10,  0.0000e+00,  1.0000e+10
  7.9185e+03,  6.3096e+08,  0.0000e+00,  6.3096e+08
  7.0949e+03,  3.9811e+07,  0.0000e+00,  3.9811e+07
  6.3208e+03,  2.5119e+06,  0.0000e+00,  2.5119e+06
  7.0375e+03,  1.5849e+05,  0.0000e+00,  1.5849e+05
  1.2809e+04,  1.0000e+04,  0.0000e+00,  1.0000e+04
  1.1300e+04,  6.3096e+02,  0.0000e+00,  6.3096e+02
  1.8861e+04,  3.9811e+01,  0.0000e+00,  3.9811e+01
  2.5919e+04,  2.5119e+00,  0.0000e+00,  2.5119e+00
  2.0754e+04,  1.5849e-01,  0.0000e+00,  1.5849e-01
  1.4429e+04,  1.0000e-02,  0.0000e+00,  1.0000e-02
  7.4963e+03,  6.3096e-04,  0.0000e+00,  6.3096e-04
  2.0233e+03,  3.9811e-05,  0.0000e+00,  3.9811e-05
  3.5679e+02,  2.5119e-06,  0.0000e+00,  2.5119e-06
  6.2803e+02,  0.0000e+00,  7.7016e+06,  0.0000e+00
*END
